### ISSUE TITLE
CRC checksum is wrong after adding metadata

### ISSUE THREAD

**Issue by chr15m** [lucach/meta-png#6]
Hi, I saw the following error from Imagemagick on an image I had modified `identify -verbose updated.png`:

```
identify: tEXt: CRC error `updated.png' @ warning/png.c/MagickPNGWarningHandler/1669.
```

Does the CRC checksum need to be updated after modifying the tEXt section?

The code was very simple: `readFileSync` then `addMetadata` with the key/value `hello` and `42`, then `writeFileSync` to a new file.

Thanks for this excellent library!

**Comment by chr15m** [comment]
Note: the image displays fine.

I found some more info. Seems like each chunk needs a CRC: https://stackoverflow.com/questions/2531389/crc-for-png-file-format

**Comment by lucach** [comment]
Hi! Thanks, I was aware of this (I even left a "use dummy CRC" comment in the code). As you noted, it is not crucial for the rest of the functionalities. 

I've finally found some time to fix it (borrowing one of the existing implementations) in 6532a7451a78dbd47f6cffe7e6852c4a00028392.
